(() => {
  const slideSrc = (number) =>
    `./assets/electrolux-slides/${String(number).padStart(2, "0")}.png`;

  const assetSrc = (name) =>
    `./assets/electrolux-slides/img/${encodeURIComponent(name)}`;

  const nav = [
    { id: "slide-03", label: "Intro" },
    { id: "slide-08", label: "Futuro" },
    { id: "slide-12", label: "Natureza Técnica" },
    { id: "slide-16", label: "Lux" },
    { id: "slide-21", label: "Poiesis" },
    { id: "slide-51", label: "Atos" },
  ];

  const sections = [
    { id: "slide-01", type: "stage", number: "01", layout: "image-only", kicker: "Abertura", media: { src: slideSrc(1), alt: "Abertura", variant: "reference", className: "stage__image--blend" } },
    { id: "slide-02", type: "stage", number: "02", layout: "image-only", kicker: "Centenário", media: { src: slideSrc(2), alt: "Centenário", variant: "cover" } },
    {
      id: "slide-03",
      type: "stage",
      number: "03",
      layout: "title-image-right",
      layoutClass: "is-center",
      kicker: "Intro",
      headline: "A casa bem vivida",
      subheadline: "Celebração de 100 anos da Electrolux no Brasil",
      media: { src: assetSrc("Frame 427321402.png"), alt: "Referência visual da casa bem vivida" },
    },
    {
      id: "slide-04",
      type: "stage",
      number: "04",
      layout: "text-page",
      kicker: "Introdução",
      paragraphs: [
        "Há 100 anos, a Electrolux transforma a vida cotidiana por meio da inovação, do design e do cuidado. Ao longo dessa trajetória, reinventou experiências de sabor, bem-estar e convivência, construindo uma relação profunda com a casa e com tudo aquilo que a torna mais significativa.",
        "É nesse contexto que surge a aproximação com a Gastroperformance.",
      ],
    },
    {
      id: "slide-05",
      type: "stage",
      number: "05",
      layout: "split",
      kicker: "Gastroperformance",
      mediaPosition: "right",
      media: { src: assetSrc("069__DSF1049 (1) 1.png"), alt: "Performance imersiva", variant: "editorial" },
      paragraphs: [
        "Criada por Simone Mattar, a Gastroperformance é uma linguagem artística que ressignifica a comida como forma de expressão e o ato de comer como gesto performático.",
        "Mais do que uma experiência gastronômica, trata-se de um acontecimento multissensorial que articula sabores, imagens, sons, espaço e presença.",
      ],
    },
    {
      id: "slide-06",
      type: "stage",
      number: "06",
      layout: "text-page",
      kicker: "Convergência",
      paragraphs: [
        "Essa aproximação com a Electrolux não acontece por acaso. Ambas compartilham valores essenciais: inovação, design, gastronomia, sustentabilidade e uma relação sensível com o público.",
      ],
    },
    {
      id: "slide-07",
      type: "stage",
      number: "07",
      layout: "text-page",
      kicker: "Memória + Força",
      paragraphs: [
        "A natureza efêmera da Gastroperformance a torna especialmente potente para celebrar um centenário. Como toda performance, ela acontece no instante, mas permanece na memória.",
        "É justamente aí que reside sua força: criar uma experiência capaz de tocar o público de forma sensível, afetiva e duradoura.",
      ],
    },
    { id: "slide-08", type: "stage", number: "08", layout: "image-only", kicker: "Futuro", headline: "Futuro", subheadline: "Exercícios de futuros possíveis", theme: "dark", cardClass: "stage__card--center-media", media: { src: "./assets/electrolux-slides/46924ccf74dd36146ae29b9ab5acde20.gif", alt: "Pulso de luz", variant: "square-small" } },
    {
      id: "slide-09",
      type: "stage",
      number: "09",
      layout: "text-page",
      kicker: "Futuro",
      paragraphs: [
        "O convite da Electrolux para imaginar os próximos 100 anos, em celebração ao século já vivido, abre espaço para pensar o futuro como um campo aberto de possibilidades, no qual se exercitam futuros possíveis.",
        "Pensar 100 anos à frente é, antes de tudo, pensar no nosso modo de existir.",
      ],
    },
    {
      id: "slide-10",
      type: "stage",
      number: "10",
      layout: "text-page",
      kicker: "Campo Sensível",
      paragraphs: [
        "A Gastroperformance se torna, assim, o meio, o campo sensível em que essas ideias ganham corpo.",
        "Por meio da comida, do espaço, da imagem, do som e da presença, o projeto transforma reflexão em experiência e faz do ato de comer uma forma de pensar poeticamente o futuro.",
      ],
    },
    {
      id: "slide-11",
      type: "stage",
      number: "11",
      layout: "split",
      kicker: "Sustentabilidade",
      mediaPosition: "right",
      media: { src: assetSrc("ego-eco-seva 1.png"), alt: "Ego eco seva", variant: "editorial-large" },
      paragraphs: [
        "Imaginar um futuro sustentável é reconhecer e reconstruir essa relação de continuidade.",
        "Desta forma, pensando na sustentabilidade como um grande desafio para as próximas gerações, seria algo natural imaginar o futuro em relação às questões que desafiam nossa existência.",
      ],
    },
    { id: "slide-12", type: "stage", number: "12", layout: "image-only", kicker: "Natureza Técnica", headline: "Natureza Técnica", subheadline: "Natural e artificial como continuidade", theme: "dark", cardClass: "stage__card--center-media", media: { src: "./assets/electrolux-slides/27bf478a3400002b729b23f275fddbf7.gif", alt: "Radiação central", variant: "square-small" } },
    {
      id: "slide-13",
      type: "stage",
      number: "13",
      layout: "text-page",
      kicker: "Natural = Artificial",
      paragraphs: [
        "A partir de uma ampla pesquisa, pensou-se que há uma imensa dicotomia em relação às noções de natural e artificial, homem-máquina e outras separações estruturais. É nessa ambiguidade que está o coração deste projeto.",
        "Nele há um deslocamento fundamental: o homem não está separado da natureza, ele está inscrito nela.",
        "Nesta Gastroperformance, desafiamos a separação de conceitos complexos em estruturas binárias, propondo a integração de ideias tratadas como opostas. O artificial não se opõe ao natural; ele emerge como um desdobramento da própria vida.",
      ],
    },
    {
      id: "slide-14",
      type: "stage",
      number: "14",
      layout: "split",
      kicker: "O Futuro",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/4e2806206a26ede382c99d783d4d74b0.gif", alt: "Reservatório de potenciais", variant: "portrait" },
      paragraphs: [
        "O futuro deixa de ser imaginado como forma pronta a ser alcançada. Ele aparece como pré-individual: um reservatório de potenciais ainda não atualizados.",
        "Pensar o tempo como contínuo significa compreender que passado, presente e futuro não estão separados, mas operam em camadas de informação, tensão e emergência.",
      ],
    },
    {
      id: "slide-15",
      type: "stage",
      number: "15",
      layout: "split",
      kicker: "Coexistência",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/4e2806206a26ede382c99d783d4d74b0.gif", alt: "Coexistência entre matéria, vida e técnica", variant: "portrait" },
      paragraphs: [
        "Imaginar futuros através da coexistência é deslocar o olhar das separações para um continuum entre matéria, vida e técnica.",
        "Ao observar padrões que atravessam do mineral aos sistemas vivos e informacionais, reconhece-se uma lógica relacional comum, onde formas emergem sem controle central.",
      ],
    },
    { id: "slide-16", type: "stage", number: "16", layout: "image-only", kicker: "Lux", headline: "Lux", subheadline: "Cone de luz e confluência temporal", theme: "dark", cardClass: "stage__card--center-media", media: { src: assetSrc("1dd3258200a7401a8e6ca9cbb79dee88 1.png"), alt: "Lux", variant: "square-small" } },
    {
      id: "slide-17",
      type: "stage",
      number: "17",
      layout: "split",
      kicker: "Cone de Luz",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/49620a3f7420f9d7e95975801fbd3c5e.gif", alt: "Faixa espectral", variant: "editorial" },
      paragraphs: [
        "Ao amanhecer, o raio de Sol não só se espalha sobre a terra, mas para o matemático Minkowski, sua luz irradia transversalmente pelo tempo.",
        "Ela irrompe a noite de ontem e cruza o dia de amanhã, alcançando o pôr do Sol de dois dias consecutivos.",
      ],
    },
    {
      id: "slide-18",
      type: "stage",
      number: "18",
      layout: "split",
      kicker: "Relatividade",
      mediaPosition: "right",
      media: { src: assetSrc("image 916.png"), alt: "Diagrama do cone de luz", variant: "contain", className: "stage__image--blend" },
      paragraphs: [
        "Em 1908, Minkowski descreveu o movimento da luz pelo espaço-tempo em um diagrama conhecido como Cone de Luz.",
        "Sua formulação abriu caminho para a Teoria da Relatividade, posteriormente desenvolvida por seu aluno, Einstein.",
        "Um pulso de luz no presente alcança os eventos do cone do futuro e é alcançado por eventos do cone do passado.",
      ],
    },
    {
      id: "slide-19",
      type: "stage",
      number: "19",
      layout: "split",
      kicker: "Irradiação",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/2e715bfa3440a668e2b125dd050104ab.gif", alt: "Irradiação azul", variant: "portrait" },
      paragraphs: [
        "Nós constantemente irradiamos ações.",
        "Sobre nós incidem irradiações do futuro e do passado, como a luz de corpos celestes no macro, e o movimento dos corpos terrestres no micro.",
        "O presente se projeta no futuro, expandindo continuamente o campo de encontros possíveis.",
      ],
    },
    {
      id: "slide-20",
      type: "stage",
      number: "20",
      layout: "text-page",
      kicker: "Confluência",
      paragraphs: [
        "Este ano é o vértice de uma confluência temporal.",
        "2026 é o ponto de simetria entre centenários.",
        "100 anos Electrolux.",
      ],
    },
    {
      id: "slide-21",
      type: "stage",
      number: "21",
      layout: "image-only",
      kicker: "Poiesis",
      headline: "Poiesis",
      subheadline: "Criação como matéria do projeto",
      theme: "dark",
      cardClass: "stage__card--center-media",
      media: { src: "./assets/electrolux-slides/22ffde53c1bdabdbc1ee7660e91d7fa3.gif", alt: "Poiesis", variant: "square-small" },
    },
    {
      id: "slide-22",
      type: "stage",
      number: "22",
      layout: "split",
      kicker: "Poíesis",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/6001a0cd585401fd91b13adfc601c56a.gif", alt: "Poíesis", variant: "portrait-large" },
      headline: "Poíesis",
      paragraphs: [
        "Poíesis é um termo grego que significa “criação”, refere-se ao processo de trazer algo à existência que antes não existia.",
      ],
    },
    {
      id: "slide-23",
      type: "stage",
      number: "23",
      layout: "split",
      kicker: "Casa",
      mediaPosition: "left",
      media: { src: assetSrc("mesa verde 2.png"), alt: "Casa como corpo expandido", variant: "portrait-large" },
      paragraphs: [
        "Ao longo de um século, a Electrolux não apenas desenvolveu tecnologias, mas participou da invenção de modos de viver.",
        "Hábitos cotidianos, interações táteis, ativações sonoras e coreografias espaciais compõem uma memória compartilhada da casa como expansão tecnológica do corpo, uma consciência coletiva que se manifesta no espaço doméstico e fora dele.",
      ],
    },
    {
      id: "slide-24",
      type: "stage",
      number: "24",
      layout: "text-page",
      kicker: "Projeto",
      paragraphs: [
        "O projeto POÉSIS é a materialização desse movimento: não apenas uma celebração dos 100 anos da Electrolux no Brasil, mas um ato de criação que torna sensível uma história construída no cotidiano das casas e das vidas que elas abrigam.",
      ],
    },
    {
      id: "slide-25",
      type: "stage",
      number: "25",
      layout: "split",
      kicker: "Tecnopoiesis",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/4fe6283f2d4222b27b8ac3e9602af7fc.gif", alt: "Tecnopoiesis", variant: "editorial" },
      paragraphs: [
        "POESIS parte dessa consciência como matéria.",
        "Recolhe, articula e transforma conceitos que não só atravessam a trajetória da marca, mas dizem respeito à nossa história como humanos, a fim de dar forma a uma experiência artístico-gastronômica onde passado, presente e futuro coexistem.",
      ],
      note: "*Tecnopoiético refere-se à capacidade criativa e poética das tecnologias na vida humana, indo além da função meramente instrumental. O conceito foca no potencial de transformação, interação e produção de sentidos (poiesis), onde máquinas e humanos co-criam novos conhecimentos e formas de vida.",
    },
    {
      id: "slide-26",
      type: "stage",
      number: "26",
      layout: "split",
      kicker: "Corpo Expandido",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/25f4df3f05201e96836437549c80e9f5.gif", alt: "Corpo expandido", variant: "editorial" },
      paragraphs: [
        "Aqui, a casa se revela como um corpo expandido e como expressão de uma inteligência coletiva: um organismo híbrido onde matéria, tecnologia e vida se articulam, prolongando o corpo para além de seus limites biológicos.",
        "A casa se torna um sistema vivo, que sente, organiza e devolve experiências.",
      ],
    },
    {
      id: "slide-27",
      type: "stage",
      number: "27",
      layout: "split",
      kicker: "Projeção",
      mediaPosition: "left",
      media: { src: "./assets/electrolux-slides/7bfdd93f6a79daf21a8df98f404b02ae.gif", alt: "Projeção", variant: "editorial" },
      paragraphs: [
        "Cada pessoa carrega em si a memória de uma casa: gestos repetidos, saberes transmitidos, ritmos herdados, futuros imaginados.",
        "Assim, POESIS não representa uma história passada, mas a projeção de futuros imaginados que se atualizam continuamente em cada presente.",
      ],
    },
    {
      id: "slide-28",
      type: "stage",
      number: "28",
      layout: "gallery-text",
      kicker: "Espaço",
      galleryLabel: "Conversation Pit",
      gallery: {
        columns: 3,
        items: [
          { src: assetSrc("CONVERSATION PIT 2.png"), alt: "Conversation pit verde" },
          { src: assetSrc("sala amarela 2.png"), alt: "Conversation pit orgânico" },
          { src: assetSrc("blog-what-is-a-tatami-room-understanding-the-japanese-style-room-1 1.png"), alt: "Tatami room" },
        ],
      },
      paragraphs: [
        "Os participantes se sentam em mesas não convencionais, mais baixas que o padrão, inspiradas no conversation pit, ambiente doméstico típico dos anos 60 e 70 pensado para criar proximidade, favorecer conversas face a face e um estado mais relaxado.",
        "São 5 mesas de 6 pessoas, totalizando 30 participantes.",
        "O espaço é inteiramente imersivo, com projeções que ocupam tanto as mesas quanto estruturas orgânicas suspensas no teto, concebidas para videomapeamento. As imagens constroem a narrativa visual dos atos, alternando-se entre essas superfícies.",
        "A operação da gastronomia é empratada à mesa, mas se desvia do formato tradicional.",
      ],
    },
    {
      id: "slide-29",
      type: "stage",
      number: "29",
      layout: "image-only",
      kicker: "Projeto",
      media: { src: assetSrc("Mesa Electrolux com Refs 16-9 1.png"), alt: "Prancha de referências espaciais", variant: "reference" },
    },
    { id: "slide-30", type: "stage", number: "30", layout: "image-only", kicker: "Planta", media: { src: assetSrc("Planta Electrolux 13_04 1.png"), alt: "Planta", variant: "full" } },
    { id: "slide-31", type: "stage", number: "31", layout: "image-only", kicker: "Espaço", media: { src: assetSrc("Mesa Electrolux Desenho 1.png"), alt: "Desenho espacial", variant: "full" } },
    { id: "slide-32", type: "stage", number: "32", layout: "image-only", kicker: "Performance", media: { src: assetSrc("image 918.png"), alt: "Render espacial", variant: "full" } },
    { id: "slide-33", type: "stage", number: "33", layout: "image-only", kicker: "Performance", media: { src: assetSrc("image 919.png"), alt: "Render espacial", variant: "full" } },
    {
      id: "slide-34",
      type: "stage",
      number: "34",
      layout: "gallery-only",
      kicker: "Luminárias",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("2063984ceee1a9ddd24df94b9c8cd48e 1.png"), alt: "Luminária etérea" },
          { src: assetSrc("a5025121a26ee40cda0499885c3f0308 1.png"), alt: "Luminária linear" },
        ],
      },
    },
    {
      id: "slide-35",
      type: "stage",
      number: "35",
      layout: "gallery-only",
      kicker: "Luminárias",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("tumblr_ngdv7uhECg1sorxqho1_640 1.png"), alt: "Luminária orgânica" },
          { src: assetSrc("a733a8f5-4d9d-4cb8-97f0-eea90a49e830_rw_1920 1.png"), alt: "Luminária orgânica" },
        ],
      },
    },
    {
      id: "slide-36",
      type: "stage",
      number: "36",
      layout: "gallery-only",
      kicker: "Projeção Suspensa",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("8b4ceff6c80c45b8eaade5705ae74a41 1.png"), alt: "Projeção suspensa" },
          { src: assetSrc("im-891032 1.png"), alt: "Projeção suspensa" },
        ],
      },
    },
    {
      id: "slide-37",
      type: "stage",
      number: "37",
      layout: "gallery-only",
      kicker: "Projeção Suspensa",
      gallery: {
        columns: 3,
        items: [
          { src: assetSrc("ecf57726995a82cccbad079c6a694786 1.png"), alt: "Cena 1", variant: "tall" },
          { src: assetSrc("16fba2-baf9eb-72a9c7.banner 1.png"), alt: "Cena 2", variant: "tall" },
          { src: assetSrc("8b4ceff6c80c45b8eaade5705ae74a41 1.png"), alt: "Cena 3", variant: "tall" },
        ],
      },
    },
    { id: "slide-38", type: "stage", number: "38", layout: "image-only", kicker: "Performance", media: { src: slideSrc(38), alt: "Performance render", variant: "full" } },
    { id: "slide-39", type: "stage", number: "39", layout: "image-only", kicker: "Performance", media: { src: slideSrc(39), alt: "Performance render", variant: "full" } },
    { id: "slide-40", type: "stage", number: "40", layout: "image-only", kicker: "Performance", media: { src: slideSrc(40), alt: "Performance render", variant: "full" } },
    { id: "slide-41", type: "stage", number: "41", layout: "image-only", kicker: "Performance", media: { src: slideSrc(41), alt: "Cena performática", variant: "full" } },
    { id: "slide-42", type: "stage", number: "42", layout: "image-only", kicker: "Performance", media: { src: slideSrc(42), alt: "Cena performática", variant: "full" } },
    { id: "slide-43", type: "stage", number: "43", layout: "image-only", kicker: "Performance", media: { src: slideSrc(43), alt: "Cena performática", variant: "full" } },
    {
      id: "slide-44",
      type: "stage",
      number: "44",
      layout: "gallery-only",
      kicker: "Projeto",
      gallery: {
        columns: 3,
        items: [
          { src: slideSrc(38), alt: "Vista 1" },
          { src: slideSrc(39), alt: "Vista 2" },
          { src: slideSrc(40), alt: "Vista 3" },
          { src: slideSrc(41), alt: "Vista 4" },
          { src: slideSrc(42), alt: "Vista 5" },
          { src: slideSrc(43), alt: "Vista 6" },
        ],
      },
    },
    {
      id: "slide-45",
      type: "stage",
      number: "45",
      layout: "text-page",
      kicker: "Conceito Gastronômico",
      paragraphs: [
        "Inspirado na relação simbólica que a cultura coreana estabelece com a fermentação, o projeto incorpora o tempo como elemento central da experiência gastronômica.",
        "A fermentação expressa um tempo que exige espera, materializando-se no alimento. Nesse contexto, o processo é pensado à luz da individuação, em que a forma emerge ao longo do devir, e da swarm intelligence, como uma inteligência distribuída, onde múltiplos agentes operam simultaneamente sem controle central, fazendo surgir o todo a partir das interações locais ao longo do tempo.",
      ],
    },
    {
      id: "slide-46",
      type: "stage",
      number: "46",
      layout: "split",
      kicker: "Conceito Gastronômico",
      mediaPosition: "left",
      media: { src: assetSrc("6479a84a19316c882d55da8b9d3f4f38 1.png"), alt: "Prato fermentado", variant: "contain" },
      paragraphs: [
        "Desenvolvido para a celebração dos 100 anos da Electrolux, o projeto parte da ideia de relativizar o tempo, compreendendo-o não apenas como um marco cronológico, mas como uma matéria ativa que atravessa toda a experiência.",
        "Na cultura coreana, a fermentação revela o tempo como um processo contínuo de transformação que acontece a partir de dentro. Ao fermentar, o tempo deixa de ser uma medida externa e passa a atuar como agente: reorganiza a matéria, altera estruturas e aprofunda sabores.",
      ],
    },
    {
      id: "slide-47",
      type: "stage",
      number: "47",
      layout: "gallery-only",
      kicker: "Conceito Gastronômico",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("92443818199e738b16a403430fef0c5a 1.png"), alt: "Prato 1", variant: "contain" },
          { src: assetSrc("82dfcdb3a4684746a7640abb3b7d8e0d 1.png"), alt: "Prato 2", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-48",
      type: "stage",
      number: "48",
      layout: "gallery-only",
      kicker: "Conceito Gastronômico",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("655ea5d2b592bdfe30f14cbeb0708ab5 1.png"), alt: "Prato 3", variant: "contain" },
          { src: assetSrc("5634c5d2391f6139654e8174829d19f0 1.png"), alt: "Prato 4", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-49",
      type: "stage",
      number: "49",
      layout: "gallery-only",
      kicker: "Conceito Gastronômico",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("429b3b8a4d1de32ecd5d07d144ace2df 1.png"), alt: "Prato 5", variant: "contain" },
          { src: assetSrc("7be9fe1de4e1cbeaa975bde568a80e1b 1.png"), alt: "Prato 6", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-50",
      type: "stage",
      number: "50",
      layout: "gallery-only",
      kicker: "Conceito Gastronômico",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("d570a08e9c56ab09f11b9988e4c2370b 1.png"), alt: "Prato 7", variant: "contain" },
          { src: assetSrc("c293b0bd921ffec9a320f3999523281b 1.png"), alt: "Prato 8", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-51",
      type: "stage",
      number: "51",
      layout: "gallery-only",
      kicker: "Atos",
      headline: "Atos",
      subheadline: "Cinco movimentos da apresentação",
      theme: "dark",
      cardClass: "stage__card--center-media",
      gallery: {
        columns: 1,
        items: [
          { src: assetSrc("Frame 427321384.gif"), alt: "Abertura dos atos", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-52",
      type: "stage",
      number: "52",
      layout: "split",
      kicker: "1º Ato - Utopia",
      mediaPosition: "left",
      media: { src: assetSrc("image 917.png"), alt: "Utopia", variant: "editorial" },
      paragraphs: [
        "A utopia não é um luxo da imaginação, mas uma função biológica de sobrevivência. Cultivar a esperança agora não é ingenuidade; é a tecnologia mais sofisticada que temos para promover futuros possíveis.",
        "É comum dizer que há o mundo utópico, e logo há o mundo real. Mas não há uma linha que os divide. Utopia não é um lugar que existe para além da realidade, mas sim uma forma de pensar sobre o presente.",
        "Oscar Wilde escreve: “Um mapa-múndi que não inclua a Utopia não é digno de consulta, pois deixa de fora o único país ao qual a Humanidade está sempre aportando.”",
      ],
    },
    { id: "slide-53", type: "stage", number: "53", layout: "image-only", kicker: "1º Ato - Utopia", media: { src: assetSrc("Escultura moderna com base de madeira 1.png"), alt: "Referência utopia", variant: "full" } },
    {
      id: "slide-54",
      type: "stage",
      number: "54",
      layout: "gallery-only",
      kicker: "1º Ato - Utopia",
      gallery: {
        columns: 3,
        items: [
          { src: assetSrc("5a0e2fc58a5cf70b57abb7fe3f34e8bc 1.png"), alt: "Cone de luz", variant: "tall" },
          { src: assetSrc("140310d001b7cba4b2fbee3a57801169 1.png"), alt: "Estrutura cristalina", variant: "tall" },
          { src: assetSrc("dd2eac6ffc4d7ba28194dab2e31fd41c 1.png"), alt: "Estrutura invertida", variant: "tall" },
        ],
      },
    },
    {
      id: "slide-55",
      type: "stage",
      number: "55",
      layout: "image-only",
      kicker: "1º Ato - Utopia",
      media: { src: assetSrc("Frame 427321409.png"), alt: "Utopia", variant: "reference" },
    },
    {
      id: "slide-56",
      type: "stage",
      number: "56",
      layout: "image-only",
      kicker: "2º Ato - Indivíduo",
      headline: "2º Ato - Indivíduo",
      subheadline: "Individuação, cristalização e metaestabilidade",
      media: { src: assetSrc("Frame 427321384-1.png"), alt: "Indivíduo", variant: "reference" },
    },
    {
      id: "slide-57",
      type: "stage",
      number: "57",
      layout: "split",
      kicker: "2º Ato - Indivíduo",
      mediaPosition: "left",
      media: { src: assetSrc("Frame 427321385.png"), alt: "Cristalização", variant: "portrait" },
      paragraphs: [
        "In dividuus, não divisível.",
        "Simondon propõe que o indivíduo não é algo dado, mas algo que se forma em processo. Antes dele, há um campo pré-individual, carregado de potenciais e tensões.",
        "A individuação é o que organiza esse campo, fazendo emergir forma — como um cristal que se estrutura a partir de um meio ainda indefinido. O indivíduo, portanto, não nasce pronto, mas emerge dessa individuação.",
      ],
    },
    {
      id: "slide-58",
      type: "stage",
      number: "58",
      layout: "split",
      kicker: "2º Ato - Indivíduo",
      mediaPosition: "left",
      media: { src: assetSrc("dadf053ee1bc3a44e3b4bc1064b47217.gif"), alt: "Campo pré-individual", variant: "editorial" },
      paragraphs: [
        "Nesse movimento, indivíduo e meio surgem juntos e seguem se transformando. Esse processo nunca se encerra completamente: todo indivíduo conserva um resto de potencial que possibilita novas transformações, mantendo-se em contínuo tornar-se.",
        "Mais do que perguntar o que algo é, trata-se de perguntar como se torna.",
        "Os objetos técnicos também se formam, se transformam e se organizam segundo dinâmicas próprias. Nessa perspectiva, “natural” e “artificial” não são opostos, mas continuidades de um mesmo processo.",
      ],
    },
    {
      id: "slide-59",
      type: "stage",
      number: "59",
      layout: "gallery-only",
      kicker: "2º Ato - Indivíduo",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("6dd700711b5f79bbdc714271e011a235 1.png"), alt: "Gelo", variant: "contain" },
          { src: assetSrc("monoammonium-phosphate-crystals-research 1.png"), alt: "Cristais", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-60",
      type: "stage",
      number: "60",
      layout: "gallery-only",
      kicker: "2º Ato - Indivíduo",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("70a47eccd053da476eeacf46387d58c9 1.png"), alt: "Espelhos", variant: "contain" },
          { src: assetSrc("Group 30.png"), alt: "Cristal translúcido", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-61",
      type: "stage",
      number: "61",
      layout: "gallery-only",
      kicker: "2º Ato - Indivíduo",
      gallery: {
        columns: 3,
        items: [
          { src: assetSrc("f007908ea68831ee6df8706adf3d5ee3 1.png"), alt: "Matéria" },
          { src: assetSrc("WhatsApp Image 2026-04-08 at 20.13.28 1.png"), alt: "Matéria 2" },
          { src: assetSrc("WhatsApp Image 2026-04-08 at 20.13.28 2.png"), alt: "Matéria 3" },
        ],
      },
    },
    {
      id: "slide-62",
      type: "stage",
      number: "62",
      layout: "gallery-only",
      kicker: "3º Ato - Redes",
      headline: "3º Ato - Redes",
      subheadline: "Continuidade entre natureza, técnica e relação",
      theme: "dark",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("Frame 427321384-2.png"), alt: "Redes 1", variant: "contain" },
          { src: assetSrc("image 816-1.png"), alt: "Redes 2", variant: "contain" },
        ],
      },
    },
    {
      id: "slide-63",
      type: "stage",
      number: "63",
      layout: "split",
      kicker: "3º Ato - Redes",
      mediaPosition: "left",
      media: { src: assetSrc("44cb629b3224e34340eede43ef267e26.gif"), alt: "Rede ontológica", variant: "editorial" },
      paragraphs: [
        "Em vez de perguntar apenas o que uma coisa é, Simondon nos ensina a perguntar como ela se torna. Para o pensador, os objetos técnicos não constituem uma exceção: também eles se formam, se transformam e se organizam segundo dinâmicas próprias.",
        "Simondon recusa a ideia de que os objetos técnicos sejam apenas instrumentos frios, subordinados ao homem como coisas sem espessura própria. Para ele, os objetos técnicos também possuem um modo de existência, uma história, uma lógica de desenvolvimento.",
      ],
    },
    {
      id: "slide-64",
      type: "stage",
      number: "64",
      layout: "split",
      kicker: "3º Ato - Redes",
      mediaPosition: "left",
      media: { src: assetSrc("b8294a0aacf3a07e6701c0fe3d16cc3e.gif"), alt: "Diagrama de relações", variant: "editorial" },
      paragraphs: [
        "Segundo essa perspectiva, o que chamamos de “natural” e “artificial” não são categorias absolutas, mas modos distintos de continuidade de um mesmo processo de formação.",
        "Ao invés de instaurar uma ruptura, a técnica é uma continuidade da natureza, transmutada pelo humano. A tecnologia amadurece, se articula e nos reorganiza, por isso deve ser compreendida como mediação viva entre o humano e o mundo.",
      ],
    },
    { id: "slide-65", type: "stage", number: "65", layout: "image-only", kicker: "3º Ato - Redes", media: { src: assetSrc("Group 31.png"), alt: "Referências para redes", variant: "reference", href: "https://br.pinterest.com/pin/20195898327606031/" } },
    {
      id: "slide-66",
      type: "stage",
      number: "66",
      layout: "image-only",
      kicker: "4º Ato - Enxame",
      headline: "4º Ato - Enxame",
      subheadline: "Inteligência coletiva e organização distribuída",
      media: { src: assetSrc("516-fe0220-swarms-01 1.png"), alt: "Enxame", variant: "reference" },
    },
    {
      id: "slide-67",
      type: "stage",
      number: "67",
      layout: "split",
      kicker: "4º Ato - Enxame",
      mediaPosition: "left",
      media: { src: assetSrc("Group 32.png"), alt: "Enxame", variant: "editorial-large" },
      paragraphs: [
        "O termo swarm intelligence descreve a inteligência coletiva que emerge da interação entre múltiplos agentes simples. Ele foi inicialmente utilizado para explicar comportamentos de espécies sociais como abelhas, formigas e pássaros.",
        "Em uma colmeia, cada abelha responde a estímulos locais. Não há um centro de comando que distribui ordens. Ainda assim, o sistema regula sua própria dinâmica com eficiência.",
      ],
    },
    {
      id: "slide-68",
      type: "stage",
      number: "68",
      layout: "split",
      kicker: "4º Ato - Enxame",
      mediaPosition: "left",
      media: { src: assetSrc("fff89a36c5ea09ba6369f29311acb29e.gif"), alt: "Potência do conjunto", variant: "editorial" },
      copyColumns: 2,
      paragraphs: [
        "Essa inteligência relacional pode ser observada em inúmeros modos de existência biológica. Abelhas, corais, camaleões e tantos outros sistemas naturais revelam formas de organização que não se apoiam em um centro único de comando, mas emergem de interações contínuas com o meio. Nesses sistemas, há uma sabedoria distribuída, construída ao longo do tempo, que sustenta sua continuidade e capacidade de adaptação.",
        "O que chamamos de inteligência coletiva pode ser entendido, então, como a potência de um conjunto que se transforma e se mantém a partir das relações entre suas partes. Modelos computacionais demonstraram que padrões complexos podem surgir de regras mínimas aplicadas em paralelo. Essa lógica inspirou algoritmos de otimização, sistemas descentralizados e pesquisas em robótica cooperativa.",
        "Para além da biologia, esse conceito sugere que inteligência não precisa estar localizada em um ponto fixo. Ela pode existir na relação entre agentes, na circulação de informação e na adaptação contínua ao ambiente.",
      ],
    },
    { id: "slide-69", type: "stage", number: "69", layout: "image-only", kicker: "4º Ato - Enxame", media: { src: assetSrc("fff89a36c5ea09ba6369f29311acb29e.gif"), alt: "Padrão de enxame", variant: "reference" } },
    {
      id: "slide-70",
      type: "stage",
      number: "70",
      layout: "split",
      kicker: "5º Ato - Poiesis",
      mediaPosition: "left",
      media: { src: assetSrc("image 868.png"), alt: "Autopoiesis", variant: "contain", className: "stage__image--blend" },
      paragraphs: [
        "O livro Autopoiesis and Cognition: The Realization of the Living (1972) dos autores, Humberto Maturana e Francisco Varela, foi fundamental para a cibernética.",
        "Eles cunham autopoiesis como a capacidade dos organismos vivos de manter e regular sua composição e definir seus limites; uma capacidade dos sistemas que surge espontaneamente de componentes e processos independentes, porém inter-relacionados. Isso implica que as propriedades isoladas dos elementos individuais não determinam os sistemas vivos. Em vez disso, essas redes, tanto vivas quanto não vivas, são compostas por elementos distribuídos.",
      ],
    },
    {
      id: "slide-71",
      type: "stage",
      number: "71",
      layout: "split",
      kicker: "5º Ato - Poiesis",
      mediaPosition: "right",
      media: { src: assetSrc("Screenshot 2026-04-13 at 13.53.41 1.png"), alt: "Livro e diagrama", variant: "contain", className: "stage__image--blend" },
      paragraphs: [
        "A autopoiesis traz à tona uma nova noção de cognição como incorporada pela diversidade de comportamentos que esses sistemas realizam.",
        "Assim, definimos a cognição quimérica como distribuída e materializada em todos os seus membros e cabeças parcialmente autônomos, alheia aos padrões de processos de pensamento de alto nível. Essa natureza heterogênea da cognição quimérica, possibilitada por cabeças e corpos coexistentes que não se substituem, parece apresentar um potencial cauteloso em direção a uma síntese simbiótica.",
      ],
    },
    {
      id: "slide-72",
      type: "stage",
      number: "72",
      layout: "gallery-only",
      kicker: "5º Ato - Poiesis",
      gallery: {
        columns: 2,
        items: [
          { src: assetSrc("image 869.png"), alt: "Mesa interativa 1" },
          { src: assetSrc("image 870.png"), alt: "Mesa interativa 2" },
        ],
      },
    },
    {
      id: "slide-73",
      type: "stage",
      number: "73",
      layout: "image-only",
      kicker: "5º Ato - Poiesis",
      media: { src: assetSrc("Frame 427321410.png"), alt: "Mesa interativa 1", variant: "reference" },
    },
    {
      id: "slide-74",
      type: "stage",
      number: "74",
      layout: "split",
      kicker: "5º Ato - Poiesis",
      mediaPosition: "left",
      media: { src: assetSrc("Frame 427321411.png"), alt: "Playtronica", variant: "editorial-large" },
      paragraphs: [
        "PLAYTRONICA - TOQUE GERA SOM",
      ],
      note: "https://www.instagram.com/p/DIcoRYRCN5t/?img_index=1",
    },
    {
      id: "slide-75",
      type: "stage",
      number: "75",
      layout: "image-only",
      kicker: "Simulação de Videomapeamento",
      media: { src: assetSrc("image 921.png"), alt: "Simulação de videomapeamento", variant: "reference", href: "https://vitormoreiran.github.io/mattar/mesa-stack.html" },
    },
    {
      id: "slide-76",
      type: "stage",
      number: "76",
      layout: "split",
      kicker: "Institucional",
      mediaPosition: "right",
      media: { src: assetSrc("Group 34.png"), alt: "Electrolux", variant: "editorial-large" },
      paragraphs: [
        "Group 34",
      ],
    },
    { id: "slide-77", type: "stage", number: "77", layout: "image-only", kicker: "Encerramento", media: { src: slideSrc(77), alt: "Encerramento", variant: "reference", className: "stage__image--blend" } },
  ];

  window.LAB_MATTAR_PAGE = {
    title: "A Casa Bem Vivida",
    eyebrow: "Electrolux x Gastroperformance",
    nav,
    sections,
  };
})();
